name: CD

on:
  push:
    branches:
      - dev
      - staging
      - production
      - main

jobs:
  deploy_to_dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy to Development
        # Your deployment steps here
        run: echo "Deploying to dev..."

  deploy_to_staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to Staging
        # Your deployment steps here
        run: echo "Deploying to staging..."

  deploy_to_prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to Production
        # Your deployment steps here
        run: echo "Deploying to production..."
